language: generic
sudo: required
dist: noble
before_script:
  - sudo snap install dotnet-sdk --classic --channel 8.0/stable
services: docker
before_install:
 - echo "We are in the right folder!"
script:
 - docker-compose build
before_deploy:
 - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag desafio-dev:lastest $DOCKER_USERNAME/desafio-dev:$TRAVIS_JOB_ID;
    docker tag postgres:lastest $DOCKER_USERNAME/postgres:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/desafio-dev:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/desafio-dev:$TRAVIS_JOB_ID;
  on:
    brach: master
notifications:
  email: false
